services:
  back:
    container_name: advanced-programming-backend
    build:
      context: .
      target: development
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
    ports:
      - '8080:8080'
